services:
  - type: web
    name: web-tech-week9
    env: node
    buildCommand: |
      apt-get update && apt-get install -y chromium \
        fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
        libxss1 \
        --no-install-recommends
      npm install
    startCommand: node app.js
    envVars:
      - key: CHROMIUM_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    plan: free
